export type Story = {
  id: number;
  slug: string;
  title: string;
  author: string;
  date: string;
  readingTime: string;
  tags: string[];
  category: string;
  image: string;
  aiHint: string;
  content: string;
  trending: boolean;
};

export const stories: Story[] = [
  {
    id: 1,
    slug: "bhabhi-ki-garam-raat",
    title: "भाभी की गरम रात",
    author: "Rahul Kumar",
    date: "2024-07-28",
    readingTime: "15 min read",
    tags: ["#भाभी", "#रात", "#पहली_बार"],
    category: "देवर-भाभी",
    image: "https://placehold.co/600x400.png",
    aiHint: "sensual couple",
    content: `रात का सन्नाटा गहरा रहा था। शहर की बत्तियां एक-एक कर बुझ रही थीं, लेकिन मेरे दिल में एक अजीब सी बेचैनी थी। आज घर में सिर्फ मैं और मेरी भाभी, रिया, थे। भैया ऑफिस के काम से बाहर गए हुए थे। रिया भाभी हमेशा से मेरे लिए एक दोस्त की तरह रही हैं, लेकिन आज उनकी मौजूदगी कुछ अलग महसूस हो रही थी।\n\nमैंने पानी पीने के बहाने किचन की ओर कदम बढ़ाए। रिया भाभी वहां पहले से ही मौजूद थीं, रात की हल्की चांदनी में उनकी silhouette बेहद खूबसूरत लग रही थी। उन्होंने मुड़कर मुझे देखा और मुस्कुराईं, "नींद नहीं आ रही, देव?" उनकी आवाज़ में शहद जैसी मिठास थी।\n\n"नहीं भाभी, बस यूँ ही," मैंने कहा और गिलास में पानी भरने लगा। हमारी नज़रें मिलीं और एक पल के लिए वक्त जैसे थम गया। उनकी आँखों में कुछ ऐसा था जो मैंने पहले कभी नहीं देखा था - एक आमंत्रण, एक रहस्य। उस एक पल ने हमारे बीच की सारी सीमाओं को धुंधला कर दिया। यह रात सिर्फ एक आम रात नहीं थी; यह एक नई कहानी की शुरुआत थी, एक ऐसी कहानी जो हम दोनों की ज़िंदगी हमेशा के लिए बदलने वाली थी।`,
    trending: true,
  },
  {
    id: 2,
    slug: "college-ka-pehla-pyaar",
    title: "कॉलेज का पहला प्यार",
    author: "Priya Sharma",
    date: "2024-07-27",
    readingTime: "12 min read",
    tags: ["#कॉलेज", "#प्यार", "#रोमांस"],
    category: "कॉलेज के दोस्त",
    image: "https://placehold.co/600x400.png",
    aiHint: "young couple",
    content: "कॉलेज के पहले दिन की वो घबराहट आज भी याद है। हजारों नए चेहरे, बड़ी-बड़ी बिल्डिंग्स और एक अजीब सा डर। उसी भीड़ में मैंने उसे पहली बार देखा था, आयशा को। उसकी हँसी में एक जादू था और उसकी आँखों में एक चमक। हमारी दोस्ती धीरे-धीरे प्यार में बदल गई। लेक्चर्स बंक करके घूमना, कैंटीन में घंटों बातें करना और एक-दूसरे के सपनों को अपना बनाना - वो दिन ही कुछ और थे। यह कहानी है उसी पहले, मासूम और दीवाने प्यार की।",
    trending: true,
  },
  {
    id: 3,
    slug: "padosan-ki-khidki",
    title: "पड़ोसन की खिड़की",
    author: "Vikram Singh",
    date: "2024-07-26",
    readingTime: "10 min read",
    tags: ["#पड़ोसन", "#खिड़की", "#फंतासी"],
    category: "पड़ोसन",
    image: "https://placehold.co/600x400.png",
    aiHint: "woman window",
    content: "मेरे बेडरूम की खिड़की ठीक उसके बेडरूम की खिड़की के सामने खुलती थी। सिमरन, मेरी नई पड़ोसन। उसे देखे बिना मेरा दिन पूरा नहीं होता था। कभी वो अपने बालों को संवारती, तो कभी गुनगुनाती। हमारी बातें आँखों-ही-आँखों में होती थीं। एक दिन, हिम्मत करके मैंने उसे एक कागज़ पर 'हाय' लिखकर दिखाया। उसने मुस्कुरा कर जवाब दिया। बस, वहीं से शुरू हुई एक अनकही, अनदेखी प्रेम कहानी।",
    trending: false,
  },
  {
    id: 4,
    slug: "office-wali-girlfriend",
    title: "ऑफिस वाली गर्लफ्रेंड",
    author: "Anjali Mehta",
    date: "2024-07-25",
    readingTime: "18 min read",
    tags: ["#ऑफिस", "#बॉस", "#सीक्रेट"],
    category: "ऑफिस अफेयर",
    image: "https://placehold.co/600x400.png",
    aiHint: "office romance",
    content: "ऑफिस का माहौल हमेशा तनावपूर्ण रहता है, लेकिन मेरे लिए वो जगह एक खूबसूरत एहसास बन गई थी। वजह थी, नेहा, मेरी कलीग। हम साथ में लंच करते, प्रोजेक्ट्स पर काम करते और धीरे-धीरे एक-दूसरे के बहुत करीब आ गए। हमारा रिश्ता ऑफिस की फाइलों में छिपा एक राज़ था। late-night काम के बहाने साथ वक्त बिताना और कॉफ़ी मशीन के पास चोरी-छुपे मिलना - यह हमारे प्यार का तरीका था।",
    trending: true,
  },
  {
    id: 5,
    slug: "baarish-mein-romance",
    title: "बारिश में रोमांस",
    author: "Aakash Verma",
    date: "2024-07-24",
    readingTime: "8 min read",
    tags: ["#बारिश", "#रोमांस", "#चाय"],
    category: "पब्लिक रोमांस",
    image: "https://placehold.co/600x400.png",
    aiHint: "rain couple",
    content: "उस शाम बारिश बहुत तेज़ थी। मैं ऑफिस से घर लौट रहा था कि अचानक बस स्टॉप पर वो मिली, भीगती हुई। मैंने उसे अपनी छतरी ऑफर की। बस, वहीं से हमारी कहानी शुरू हुई। बारिश की बूंदों के साथ हमारी बातें, चाय की चुस्कियों के साथ हमारी हँसी और भीगी सड़कों पर साथ चलना। उस बारिश ने हमें हमेशा के लिए एक-दूसरे से जोड़ दिया।",
    trending: false,
  },
  {
    id: 6,
    slug: "anjaan-safar",
    title: "अनजान सफ़र",
    author: "Kavita Reddy",
    date: "2024-07-23",
    readingTime: "20 min read",
    tags: ["#ट्रेन", "#सफ़र", "#अजनबी"],
    category: "ट्रेन या बस में",
    image: "https://placehold.co/600x400.png",
    aiHint: "train journey",
    content: "वो एक लंबी ट्रेन यात्रा थी। मैं अपनी सीट पर बैठा किताबें पढ़ रहा था, तभी वो सामने आकर बैठी। उसकी आँखों में एक अजीब सी उदासी थी। हमने बातें शुरू कीं और पता चला कि हम दोनों एक ही मंज़िल के मुसाफिर हैं। 24 घंटे के उस सफ़र में हमने अपनी पूरी ज़िंदगी एक-दूसरे से बांट ली। वो सफ़र खत्म हो गया, लेकिन हमारी कहानी वहीं से शुरू हुई।",
    trending: false,
  },
  {
    id: 7,
    slug: "saree-wali-aunty",
    title: "साड़ी वाली आंटी",
    author: "Rohan Mehra",
    date: "2024-07-22",
    readingTime: "14 min read",
    tags: ["#आंटी", "#साड़ी", "#मोहल्ला"],
    category: "आंटी",
    image: "https://placehold.co/600x400.png",
    aiHint: "woman in saree",
    content: "हमारे मोहल्ले में एक आंटी थीं, निशा आंटी। सब उन्हें साड़ी वाली आंटी कहते थे क्योंकि वो हमेशा खूबसूरत साड़ियों में रहती थीं। मैं अक्सर उन्हें छत पर कपड़े सुखाते हुए देखता था। उनकी मुस्कान में एक अजीब सी कशिश थी। एक दिन पतंग उड़ाते हुए मेरी पतंग उनकी छत पर जा गिरी। मैं हिचकिचाते हुए उनकी घंटी बजाई। उन्होंने दरवाजा खोला और मुस्कुराकर मेरी पतंग दी। उस दिन के बाद हमारी बातें शुरू हुईं और मैं उनके अनुभव और समझ का कायल हो गया।",
    trending: true,
  },
  {
    id: 8,
    slug: "train-wali-stranger",
    title: "ट्रेन वाली अजनबी",
    author: "Sneha Gupta",
    date: "2024-07-21",
    readingTime: "11 min read",
    tags: ["#अजनबी", "#ट्रेन", "#प्यार"],
    category: "अजनबी",
    image: "https://placehold.co/600x400.png",
    aiHint: "woman on train",
    content: "दिल्ली से मुंबई की उस रात की ट्रेन में मेरी बगल वाली सीट पर वो बैठी थी। उसके हाथ में एक किताब थी और चेहरे पर एक मासूमियत। हमने एक-दूसरे को देखा और मुस्कुराए। बातों का सिलसिला शुरू हुआ तो पता ही नहीं चला कि कब सुबह हो गई। स्टेशन पर उतरते वक्त हमने एक-दूसरे के नंबर लिए, यह वादा करते हुए कि हम फिर मिलेंगे। वो अजनबी अब मेरी ज़िंदगी का सबसे अहम हिस्सा है।",
    trending: false,
  },
  {
    id: 9,
    slug: "bhabhi-ka-secret",
    title: "भाभी का राज़",
    author: "Amit Desai",
    date: "2024-07-20",
    readingTime: "16 min read",
    tags: ["#देवर-भाभी", "#राज़", "#भरोसा"],
    category: "देवर-भाभी",
    image: "https://placehold.co/600x400.png",
    aiHint: "whispering secret",
    content: "मैं और मेरी भाभी हमेशा से अच्छे दोस्त थे। हम एक-दूसरे से सब कुछ शेयर करते थे। एक रात, जब भैया घर पर नहीं थे, तो भाभी बहुत उदास थीं। मैंने वजह पूछी तो उन्होंने मुझे अपने एक पुराने राज़ के बारे में बताया। उस रात मैंने उन्हें संभाला और हमारा रिश्ता और भी गहरा हो गया। यह कहानी है भरोसे और दोस्ती की, जो किसी भी रिश्ते से बढ़कर है।",
    trending: true,
  },
  {
    id: 10,
    slug: "shaadi-ki-saalgirah",
    title: "शादी की सालगिरह",
    author: "Meera Patel",
    date: "2024-07-19",
    readingTime: "9 min read",
    tags: ["#पति-पत्नी", "#सालगिरह", "#सरप्राइज"],
    category: "पति-पत्नी",
    image: "https://placehold.co/600x400.png",
    aiHint: "romantic dinner",
    content: "आज हमारी शादी की पांचवीं सालगिरह थी। रोहित सुबह से ही अजीब सा व्यवहार कर रहा था। मुझे लगा वो भूल गया। मैं थोड़ी नाराज़ थी। शाम को जब वो घर आया तो पूरा घर अंधेरे में डूबा था। मैं कुछ कहती, उससे पहले ही उसने लाइट जलाई। पूरा कमरा फूलों और मोमबत्तियों से सजा था। उसने मेरे लिए एक खूबसूरत सरप्राइज प्लान किया था। वो रात हमारे प्यार की सबसे यादगार रातों में से एक बन गई।",
    trending: false,
  },
  {
    id: 11,
    slug: "long-distance-love",
    title: "लॉन्ग डिस्टेंस वाला प्यार",
    author: "Karan Joshi",
    date: "2024-07-18",
    readingTime: "13 min read",
    tags: ["#BF-GF", "#लॉन्ग_डिस्टेंस", "#इंतजार"],
    category: "BF-GF",
    image: "https://placehold.co/600x400.png",
    aiHint: "video call",
    content: "मैं और रिया एक ही शहर में पले-बढ़े, लेकिन करियर ने हमें अलग-अलग शहरों में पहुंचा दिया। हमारा प्यार अब वीडियो कॉल्स और चैट्स पर ज़िंदा था। दूर रहकर प्यार निभाना आसान नहीं था, लेकिन हमारे बीच का भरोसा और प्यार हर मुश्किल पर भारी पड़ा। यह कहानी है उस इंतजार, उस तड़प और उस विश्वास की जो लॉन्ग डिस्टेंस रिलेशनशिप को भी खूबसूरत बना देती है।",
    trending: true,
  },
  {
    id: 12,
    slug: "college-crush",
    title: "कॉलेज क्रश",
    author: "Alok Nath",
    date: "2024-07-17",
    readingTime: "10 min read",
    tags: ["#कॉलेज_के_दोस्त", "#क्रश", "#हिम्मत"],
    category: "कॉलेज के दोस्त",
    image: "https://placehold.co/600x400.png",
    aiHint: "shy student",
    content: "लाइब्रेरी की उस शांत सी लड़की पर मेरा दिल आ गया था। मैं उसे रोज़ देखता, लेकिन कभी बात करने की हिम्मत नहीं हुई। वो मेरी क्रश थी। मेरे दोस्त मुझे चिढ़ाते थे। फेयरवेल पार्टी के दिन मैंने फैसला किया कि आज मैं उससे अपने दिल की बात कह दूँगा। मैंने उसे डांस के लिए पूछा और उसने हाँ कर दी। उस रात की बात कुछ और थी।",
    trending: false,
  },
  {
    id: 13,
    slug: "boss-ke-saath-trip",
    title: "बॉस के साथ ट्रिप",
    author: "Tina D'souza",
    date: "2024-07-16",
    readingTime: "19 min read",
    tags: ["#ऑफिस_अफेयर", "#बॉस", "#ट्रिप"],
    category: "ऑफिस अफेयर",
    image: "https://placehold.co/600x400.png",
    aiHint: "business travel",
    content: "मेरे बॉस, मिस्टर शर्मा, बहुत ही सख्त और प्रोफेशनल थे। लेकिन जब हम एक कॉन्फ्रेंस के लिए शिमला गए, तो मैंने उनका एक अलग ही रूप देखा। काम के बाद हम साथ घूमते, बातें करते। पहाड़ों की ठंड और शांत माहौल ने हमारे बीच की प्रोफेशनल दीवार को गिरा दिया। वो ट्रिप हमारे रिश्ते में एक नया मोड़ लेकर आई।",
    trending: true,
  },
  {
    id: 14,
    slug: "padosan-ka-dupatta",
    title: "पड़ोसन का दुपट्टा",
    author: "Ravi Verma",
    date: "2024-07-15",
    readingTime: "7 min read",
    tags: ["#पड़ोसन", "#दुपट्टा", "#इशारा"],
    category: "पड़ोसन",
    image: "https://placehold.co/600x400.png",
    aiHint: "woman balcony",
    content: "एक दिन हवा से उड़कर मेरी पड़ोसन का दुपट्टा मेरी बालकनी में आ गिरा। मैं उसे देने गया। वो दरवाज़े पर आई, उसकी आँखों में एक शरारत थी। उसने दुपट्टा लेते हुए मेरे हाथ को छुआ। बस, उस एक स्पर्श ने मेरे दिल में हलचल मचा दी। उसके बाद से हमारी मुलाकातों का सिलसिला शुरू हो गया।",
    trending: false,
  },
  {
    id: 15,
    slug: "pehli-chuan",
    title: "पहली छुअन",
    author: "Aditi Singh",
    date: "2024-07-14",
    readingTime: "11 min read",
    tags: ["#पहली_बार", "#छुअन", "#एहसास"],
    category: "पहली बार",
    image: "https://placehold.co/600x400.png",
    aiHint: "holding hands",
    content: "हम दोनों दोस्त थे, सबसे अच्छे दोस्त। लेकिन हमारे दिलों में कुछ और ही था। एक शाम, हम मूवी देख रहे थे। अचानक मेरा हाथ उसके हाथ से टकराया। एक बिजली सी दौड़ गई पूरे शरीर में। हमने एक-दूसरे को देखा। वो पहली छुअन का एहसास आज भी मेरे रोंगटे खड़े कर देता है। उस दिन हमारी दोस्ती ने प्यार का पहला कदम बढ़ाया था।",
    trending: true,
  }
];

export const categories = [
  { title: "आंटी", image: "https://placehold.co/300x400.png", aiHint: 'mature woman' },
  { title: "अजनबी", image: "https://placehold.co/300x400.png", aiHint: 'strangers meeting' },
  { title: "देवर-भाभी", image: "https://placehold.co/300x400.png", aiHint: 'family romance' },
  { title: "पति-पत्नी", image: "https://placehold.co/300x400.png", aiHint: 'husband wife' },
  { title: "BF-GF", image: "https://placehold.co/300x400.png", aiHint: 'young couple' },
  { title: "कॉलेज के दोस्त", image: "https://placehold.co/300x400.png", aiHint: 'college friends' },
  { title: "ऑफिस अफेयर", image: "https://placehold.co/300x400.png", aiHint: 'office romance' },
  { title: "पड़ोसन", image: "https://placehold.co/300x400.png", aiHint: 'woman looking' },
  { title: "पहली बार", image: "https://placehold.co/300x400.png", aiHint: 'first time' },
  { title: "दोस्त", image: "https://placehold.co/300x400.png", aiHint: 'friends talking' },
  { title: "शादीशुदा महिलाएं", image: "https://placehold.co/300x400.png", aiHint: 'married woman' },
  { title: "पति की कमी", image: "https://placehold.co/300x400.png", aiHint: 'lonely woman' },
  { title: "रिश्तेदार", image: "https://placehold.co/300x400.png", aiHint: 'family gathering' },
  { title: "फैंटेसी", image: "https://placehold.co/300x400.png", aiHint: 'fantasy world' },
  { title: "गर्मी से भरी रातें", image: "https://placehold.co/300x400.png", aiHint: 'hot night' },
  { title: "डॉक्टर-मरीज", image: "https://placehold.co/300x400.png", aiHint: 'doctor patient' },
  { title: "टीचर-स्टूडेंट", image: "https://placehold.co/300x400.png", aiHint: 'teacher student' },
  { title: "सास और बहू", image: "https://placehold.co/300x400.png", aiHint: 'family argument' },
  { title: "बड़े भाई और छोटी बहन", image: "https://placehold.co/300x400.png", aiHint: 'sibling bond' },
  { title: "रूममेट", image: "https://placehold.co/300x400.png", aiHint: 'roommates talk' },
  { title: "पब्लिक रोमांस", image: "https://placehold.co/300x400.png", aiHint: 'public romance' },
  { title: "ट्रेन या बस में", image: "https://placehold.co/300x400.png", aiHint: 'train journey' },
  { title: "कालेज की लास्ट बेंच", image: "https://placehold.co/300x400.png", aiHint: 'college classroom' },
  { title: "पार्टी और नाइटआउट", image: "https://placehold.co/300x400.png", aiHint: 'party night' },
  { title: "समर वेकेशन", image: "https://placehold.co/300x400.png", aiHint: 'summer beach' },
  { title: "फैमिली गेदरिंग", image: "https://placehold.co/300x400.png", aiHint: 'family dinner' },
  { title: "पति का ऑफिस ट्रिप", image: "https://placehold.co/300x400.png", aiHint: 'business trip' },
  { title: "रहस्यमय प्रेमी", image: "https://placehold.co/300x400.png", aiHint: 'mysterious man' },
  { title: "दूसरा प्यार", image: "https://placehold.co/300x400.png", aiHint: 'second chance' },
  { title: "गुप्त मुलाकातें", image: "https://placehold.co/300x400.png", aiHint: 'secret meeting' },
];
